# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'WeatherApp' do
	# Uncomment the next line if you're using Swift or would like to use dynamic frameworks
	use_frameworks!
	
	pod 'SVPullToRefresh', '0.4.1'
	pod 'RestKit', '0.27.1'
	pod 'SDWebImage', '3.7.3'
	
	pod 'ResplendentUtilities', '0.5.2'
	pod 'RTSMTableSectionManager', '0.1.9'
	pod 'RUTextSize', '0.1.15'
	pod 'ResplendentRestkit', '0.2.1'
	
end
